services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farasi_api_dev
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    volumes:
      - ./backend:/app # live code reload
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: farasi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT:-5438}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
