# FROM node:22-bullseye

# WORKDIR /app

# # Copy lock files first for caching
# COPY package.json pnpm-lock.yaml ./

# # Install pnpm globally and dependencies
# RUN npm install -g pnpm \
#   && pnpm install

# # Copy all source files
# COPY . .

# EXPOSE 3000

# CMD ["pnpm", "run", "start:dev", "--", "--watch"]
